version: '3.4'
services:
  php:
    container_name: klaxoon_php
    build:
      context: ./docker
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      COMPOSER_HOME: /tmp/composer
  mysql:
    container_name: klaxoon_bdd
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
